# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-25 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_auto_20170125_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='age',
            field=models.CharField(choices=[('18', '18 - 24'), ('25', '25 - 34'), ('35', '35 - 44'), ('45', '45 - 54'), ('55', '55 - 64'), ('65', '65+')], default=None, max_length=2, null=True),
        ),
    ]
