# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_delete_noconsent'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoConsent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, max_length=500)),
                ('when', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
