# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-27 13:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_auto_20170127_1119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='english_level',
            field=models.CharField(blank=True, choices=[('6', 'high advanced'), ('5', 'low advanced'), ('4', 'high intermediate'), ('3', 'low intermediate'), ('2', 'high beginner'), ('1', 'low beginner')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='living_now',
            field=models.CharField(blank=True, choices=[(True, 'Yes'), (False, 'No')], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='years_in_esc',
            field=models.CharField(blank=True, choices=[('0', 'never'), ('1', '1 - 12 months'), ('2', '1 - 2 years'), ('3', '3 - 4'), ('5', 'more than 5 years')], max_length=1, null=True),
        ),
    ]
