# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 17:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_auto_20170127_1313'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnglishTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.CharField(max_length=10)),
                ('passed', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.Participant')),
            ],
        ),
    ]
