# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 20:07
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_englishtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishtest',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
