# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-01-28 20:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_auto_20170128_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='englishtest',
            name='passed',
            field=models.NullBooleanField(),
        ),
    ]
