# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-06 14:21
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0017_auto_20170129_1443'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sentence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(blank=True, max_length=300, null=True)),
                ('s2', models.CharField(blank=True, max_length=300, null=True)),
                ('s3', models.CharField(blank=True, max_length=300, null=True)),
                ('s3_expression_change', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=None, max_length=1, null=True)),
                ('s3_expression', models.CharField(choices=[('0', 'thoughtful'), ('1', 'bored'), ('2', 'confused'), ('3', "I don't know")], default=None, max_length=1, null=True)),
                ('s3_reason', models.CharField(choices=[('0', 'my sentence was boring'), ('1', 'there was a grammar/vocabulary mistake in my sentence'), ('2', 'it changed randomly'), ('3', "I don't know")], default=None, max_length=1, null=True)),
                ('s4', models.CharField(blank=True, max_length=300, null=True)),
                ('s5', models.CharField(blank=True, max_length=300, null=True)),
                ('s5_expression_change', models.CharField(choices=[('1', 'Yes'), ('0', 'No')], default=None, max_length=1, null=True)),
                ('s6', models.CharField(blank=True, max_length=300, null=True)),
                ('person', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
