# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-13 21:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_auto_20170213_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentence',
            name='s3_expression',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='s3_reason',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='s5_expression_change',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sentence',
            name='s6_expression_change',
            field=models.CharField(default=None, max_length=1, null=True),
        ),
    ]
