# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-02-15 14:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0024_auto_20170215_1241'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='englishtest',
            name='passed',
        ),
        migrations.AlterField(
            model_name='englishtest',
            name='answers',
            field=models.CharField(max_length=15),
        ),
    ]
